#!/bin/bash
#SBATCH -J ivy_pancreas_project_darcy
#SBATCH --output=pancreas_project.o%j
#SBATCH --error=pancreas_project.e%j
#SBATCH -p himem-ivy #nocona
#SBATCH -N 2
#SBATCH --ntasks-per-node=20
#SBATCH --mem-per-cpu=60GB
#SBATCH -t 40:00:00
export OMP_NUM_THREADS=1
mpirun -np 40 python YifanMonolithic.py > hpcc.log 
